### ISSUE TITLE
wasme deploy envoy not reding config value

### ISSUE THREAD

**Issue by salrashid123** [solo-io/wasm#193]
the configuration string does't seem to get read in while  deploying as local envoy:

```bash
$ wasme --version
wasme version 0.0.26

$ wasme deploy envoy webassemblyhub.io/salrashid123/add-header:latest \
      --config '{"name": "plugin configuration","value": "some value"}' \
      --envoy-image  istio/proxyv2:1.7.3 -v
```

shows 

```yaml
DEBU[0000] exec: [docker run --rm --name my_root_id --entrypoint envoy -v /home/srashid/.wasme/store/0276212f01b5c227c466eec5d1fc8761:/home/srashid/.wasme/store/0276212f01b5c227c466eec5d1fc8761:ro -p 8080:8080 -p 19000:19000 istio/proxyv2:1.7.3 --disable-hot-restart --config-yaml admin:
  accessLogPath: /dev/null
  address:
    socketAddress:
      address: 0.0.0.0
      portValue: 19000
staticResources:
  clusters:
  - connectTimeout: 0.250s
    dnsLookupFamily: V4_ONLY
    hosts:
    - socketAddress:
        address: jsonplaceholder.typicode.com
        ipv4Compat: true
        portValue: 443
    name: static-cluster
    tlsContext:
      sni: jsonplaceholder.typicode.com
    type: LOGICAL_DNS
  listeners:
  - address:
      socketAddress:
        address: 0.0.0.0
        portValue: 8080
    filterChains:
    - filters:
      - config:
          httpFilters:
          - config:
              config:
                name: my_root_id
                rootId: my_root_id
                vmConfig:
                  code:
                    local:
                      filename: /home/srashid/.wasme/store/0276212f01b5c227c466eec5d1fc8761/filter.wasm
                  runtime: envoy.wasm.runtime.v8
                  vmId: my_root_id
            name: envoy.filters.http.wasm
          - name: envoy.router
          routeConfig:
            name: test
            virtualHosts:
            - domains:
              - '*'
              name: jsonplaceholder
              routes:
              - match:
                  prefix: /
                route:
                  autoHostRewrite: true
                  cluster: static-cluster
          statPrefix: ingress_http
        name: envoy.http_connection_manager
    name: listener_0
]
```

i expect the config value to get read a inline config like

```yaml
      filterChains:
      - filters:
        - config:
            httpFilters:
            - config:
                config:
                  name: my_root_id
                  rootId: my_root_id
                  configuration:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: |
                      {
                        "name": "plugin configuration",
                        "value": "some value"
                      }                  
                  vmConfig:
                    code:
                      local:
```
