### ISSUE TITLE
Wasm support istio 1.8.1 is not perfect

### ISSUE THREAD

**Issue by tanjunchen** [solo-io/wasm#245]
**Describe the bug**

The istio cluster (including the revision field) deployed by istio-operator is not supported by wasm. By default, wasm.io reads the name of the deployment istiod, as seen in the code in  https://github.com/solo-io/wasm/blob/master/tools/wasme/cli/pkg/deploy/istio/get_istio_version.go#L30 .

the yaml of deploy istio cluster is 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane-1-8-1
spec:
  revision: 1-8-1
  profile: demo
```

**To Reproduce**
1. install k8s cluster
2. install istio cluster with above yaml
3. test the example of wasm according to https://docs.solo.io/web-assembly-hub/latest/tutorial_code/deploy_tutorials/deploying_with_istio/

**Expected behavior**

Provide support parameter revision for reading the deployment name of istiod.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version
- Istio version
Istio 1.8.1
