### ISSUE TITLE
wasm deploy can not create envoyfilter

### ISSUE THREAD

**Issue by junji2** [solo-io/wasm#266]
istio version 1.9.3
kubernetes version 1.20.4
operator version quay.io/solo-io/wasme:0.0.32

filterDeployment.yaml:
```
apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: myfilter
  namespace: nginx
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    image: webassemblyhub.io/qiujj/header_test:v0.2
```

after I run the command:
```
k apply -f filterDeployment.yaml
```

wasme operate log:
```
time="2021-06-19T05:57:34Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:35Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:36Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:38Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:38Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:40Z" level=warning msg="event err: expected 1 image-ready events for image webassemblyhub.io/qiujj/header_test:v0.2, only found map[]"
time="2021-06-19T05:57:40Z" level=info msg="cleaning up cache events for image webassemblyhub.io/qiujj/header_test:v0.2"
time="2021-06-19T05:57:40Z" level=info msg="updated workload sidecar annotations" filter="id:\"myfilter.nginx\" image:\"webassemblyhub.io/qiujj/header_test:v0.2\" rootID:\"2021-06-19header-test\" " workload=nginx-sample-server-v1
```
it stopped at 'updated workload sidecar annotations' and did not connitue to 'created Istio EnvoyFilter resource '

Have you ever encountered this situation
